### ISSUE TITLE
Fix ability to add new pages 

### ISSUE THREAD

**Issue by gjacobs86** [gjacobs86/openarchcollab.org#62]
Every time I try to create a new page I get an error that tells me to go to the first function of code in /app/views/category.html:3 or /app/views/htmlpage.html:3 

It seems like there is a red highlight around an ampersand in line 9 - might that be the issue? 

I need to be able to add more pages to the site asap for our leaders in Venice who are doing outreach for the venice biennale right now. 

Thanks!
G

**Comment by davidrleonard** [comment]
Custom pages can be accessed without having to add the ending `page` by creating a URL like...

http://openarchcollab.org/page/page_id_in_here

Fixed in 97b1966d8291f1081304e06572200d03f2e047bf
