### ISSUE TITLE
Setup local dev environments

### ISSUE THREAD

**Issue by atav32** [gjacobs86/openarchcollab.org#70]
- [x] Brian
- [x] Sam

**Comment by atav32** [comment]
@fureigh I'm reading through the install docs and it says Drupal is compatible with a bunch of web technologies. Do you know which ones we've picked for OAC? I want to mirror the prod env as much as possible.

1. Web server: Apache or Nginx?
2. PHP: Is there a recommended version?
3. Database: MySQL, MariaDB, Percona, Postgres, SQLite?

**Comment by distal-shores** [comment]
Getting hung up at `git clone` stage, need a password. @fureigh if you get a chance, fire it over on Slack or email. :)

**Comment by atav32** [comment]
Just to document my progress,

I got things working with,
- latest version of Apache
- PHP 7.1 with OPcache
- latest version of MySQL (imported the test DB from Pantheon)

but I couldn't find where the image assets were stored

**Comment by distal-shores** [comment]
Looks like both Brian and I are up and running at this point.
