### ISSUE TITLE
Get @atav32 and @distal-shores access to their accounts

### ISSUE THREAD

**Issue by fureigh** [gjacobs86/openarchcollab.org#71]
* [x] @fureigh, send remaining access info to @atav32 and @distal-shores so they can log into their dev environments.
* [x] @atav32 and @distal-shores, please confirm that you're able to log in.

**Comment by distal-shores** [comment]
I'm able to log in to Pantheon and access the development sandbox without any issue.

**Comment by atav32** [comment]
Sweet, looks like we're good
